<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Transformer;

/**
 * Class PostAbstract
 * @package B2W\SkyHub\Model\Transformer
 */
abstract class PostAbstract
{
    /**
     * @var array
     */
    protected $_map = array();

    /**
     * @param $post
     * @param $entity
     * @return PostAbstract|bool
     */
    public static function convert($post, $entity)
    {
        static $instance = false;
        if ($instance === false) {
            $instance = new static();
        }

        $instance->_init();
        $instance->_convert($post, $entity);

        return $instance;
    }

    /**
     * PostAbstract constructor.
     */
    private function __construct()
    {
        return $this;
    }

    /**
     * @return $this
     */
    private function __clone()
    {
        return $this;
    }

    /**
     * @return mixed
     */
    abstract protected function _init();

    /**
     * @param $postAttribute
     * @param $entityAttribute
     * @return $this
     */
    protected function _addMap($postAttribute, $entityAttribute)
    {
        $this->_map[$postAttribute] = $entityAttribute;
        return $this;
    }

    /**
     * @param $post
     * @param $entity
     * @return $this
     */
    protected function _convert($post, $entity)
    {
        $meta = get_post_meta($post->ID);

        foreach ($this->_map as $postAttribute => $entityAttribute) {

            if (empty($postAttribute)) {
                continue;
            }

            $method = 'set' . ucfirst($entityAttribute);
            if (!method_exists($entity, $method)) {
                continue;
            }

            $value = property_exists($post, $postAttribute)
                ? $post->$postAttribute
                : (key_exists($postAttribute, $meta) ? current($meta[$postAttribute]) : null);

            if (!$value) {
                continue;
            }

            $entity->$method($value);
        }

        //SET ADDITIONAL DATA
        if (method_exists($entity, 'setAdditional')) {
            foreach ($post->to_array() as $key => $value) {
                if (isset($this->_map[$key])) {
                    continue;
                }

                $entity->setAdditional($key, $value);
            }
        }

        return $this;
    }
}
