<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Contracts\Resource\Sales\Order\Repository;

use B2W\SkyHub\Contracts\Sales\Order\Entity;

/**
 * Interface Db
 * @package B2W\SkyHub\Contracts\Sales\Order\Repository
 */
interface Db
{
    /**
     * @param $filter
     * @return mixed
     */
    public function find($filter);

    /**
     * @param $post
     * @return mixed
     */
    public function one($post);

    /**
     * @param Entity $order
     * @return mixed
     */
    public function save(Entity $order);
}
