<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\Skyhub\Model\Catalog\Product\Specification;

use B2W\Skyhub\Model\Data\CollectionAbstract;

/**
 * Class Collection
 * @package B2W\Skyhub\Model\Catalog\Product\Specification
 */
class Collection extends CollectionAbstract
{
}
