<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Catalog\Product\Variation;


/**
 * Class Entity
 * @package B2W\SkyHub\Model\Catalog\Product\Variation
 */
class Entity implements \B2W\SkyHub\Contracts\Catalog\Product\Variation\Entity
{
    /**
     *
     */
    const POST_TYPE     = 'product_variation';
    /**
     *
     */
    const META_IMAGE = '_thumbnail_id';

    /**
     * @var null
     */
    protected $_id              = null;
    /**
     * @var null
     */
    protected $_sku             = null;
    /**
     * @var null
     */
    protected $_qty             = null;
    /**
     * @var null
     */
    protected $_ean             = null;
    /**
     * @var array
     */
    protected $_images          = null;
    /**
     * @var null
     */
    protected $_specifications  = null;
    /**
     * @var null
     */
    protected $_parent          = null;
    /**
     * @var null
     */
    protected $_parentId = null;
    /**
     * @var null
     */
    protected $_price = null;

    /**
     * @param \B2W\SkyHub\Contracts\Catalog\Product\Entity $product
     * @return $this|mixed
     */
    public function setParent(\B2W\SkyHub\Contracts\Catalog\Product\Entity $product)
    {
        $this->_parent = $product;
        return $this;
    }

    /**
     * @return mixed|null
     * @throws \B2W\SkyHub\Exception\Data\RepositoryNotFound
     */
    public function getParent()
    {
        if (is_null($this->_parent) && !empty($this->_parentId)) {
            $this->_parent = \App::repository(\App::REPOSITORY_CATALOG_PRODUCT)->one($this->_parentId);
        }

        return $this->_parent;
    }

    /**
     * @return null
     */
    public function getParentId()
    {
        if (empty($this->_parentId) && $this->_parent) {
            $this->_parentId = $this->_parent->getId();
        }

        return $this->_parentId;
    }

    /**
     * @param null $parentId
     */
    public function setParentId($parentId)
    {
        $this->_parentId = $parentId;
    }


    /**
     * @return null
     */
    public function getId()
    {
        return $this->_id;
    }

    /**
     * @param null $id
     * @return Entity
     */
    public function setId($id)
    {
        $this->_id = $id;
        return $this;
    }

    /**
     * @return null
     */
    public function getSku()
    {
        return $this->_sku;
    }

    /**
     * @param null $sku
     * @return Entity
     */
    public function setSku($sku)
    {
        $this->_sku = $sku;
        return $this;
    }

    /**
     * @return null
     */
    public function getQty()
    {
        return $this->_qty;
    }

    /**
     * @param null $qty
     * @return Entity
     */
    public function setQty($qty)
    {
        $this->_qty = $qty;
        return $this;
    }

    /**
     * @return null
     */
    public function getEan()
    {
        return $this->_ean;
    }

    /**
     * @param null $ean
     * @return Entity
     */
    public function setEan($ean)
    {
        $this->_ean = $ean;
        return $this;
    }

    /**
     * @return array
     */
    public function getImages()
    {
        return $this->_images;
    }

    /**
     * @param $images
     * @return $this|mixed
     */
    public function setImages($images)
    {
        $this->_images = $images;
        return $this;
    }

    /**
     * @return mixed|null
     * @throws \Exception
     */
    public function getSpecifications()
    {
        if (is_null($this->_specifications)) {
            $this->_loadSpecifications();
        }

        return $this->_specifications;
    }

    /**
     * @param $specifications
     * @return $this|mixed
     */
    public function setSpecifications($specifications)
    {
        $this->_specifications = $specifications;
        return $this;
    }

    /**
     * @return null
     */
    public function getPrice()
    {
        return $this->_price;
    }

    /**
     * @param null $price
     */
    public function setPrice($price)
    {
        $this->_price = $price;
    }

}
