<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\Skyhub\Model\Catalog\Product\Variation;


class Entity implements \B2W\Skyhub\Contracts\Catalog\Product\Variation\Entity
{
    const POST_TYPE = 'product_variation';

    protected $_id              = null;
    protected $_sku             = null;
    protected $_qty             = null;
    protected $_ean             = null;
    protected $_images          = array();
    protected $_specifications  = null;

    /**
     * @return null
     */
    public function getId()
    {
        return $this->_id;
    }

    /**
     * @param null $id
     * @return Entity
     */
    public function setId($id)
    {
        $this->_id = $id;
        return $this;
    }

    /**
     * @return null
     */
    public function getSku()
    {
        return $this->_sku;
    }

    /**
     * @param null $sku
     * @return Entity
     */
    public function setSku($sku)
    {
        $this->_sku = $sku;
        return $this;
    }

    /**
     * @return null
     */
    public function getQty()
    {
        return $this->_qty;
    }

    /**
     * @param null $qty
     * @return Entity
     */
    public function setQty($qty)
    {
        $this->_qty = $qty;
        return $this;
    }

    /**
     * @return null
     */
    public function getEan()
    {
        return $this->_ean;
    }

    /**
     * @param null $ean
     * @return Entity
     */
    public function setEan($ean)
    {
        $this->_ean = $ean;
        return $this;
    }

    /**
     * @return array
     */
    public function getImages()
    {
        return $this->_images;
    }

    public function addImage($image)
    {
        $this->_images[] = $image;
        return $this;
    }

    /**
     * @return null
     */
    public function getSpecifications()
    {
        return $this->_specifications;
    }

    /**
     * @param null $specifications
     * @return Entity
     */
    public function addSpecification(\B2W\Skyhub\Contracts\Catalog\Product\Specification\Entity $specification)
    {
        $this->_specifications = $specification;
        return $this;
    }
}
