<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Customer\Repository;

use B2W\SkyHub\Contracts\Resource\Repository;
use B2W\SkyHub\Exception\Customer\CustomerInstance;
use B2W\SkyHub\Model\Customer\Collection;
use B2W\SkyHub\Model\Customer\Entity;
use B2W\SkyHub\Model\Resource\RepositoryAbstract;
use B2W\SkyHub\Model\Resource\Select;
use B2W\SkyHub\Model\Transformer\User\Customer;

/**
 * Class Db
 * @package B2W\SkyHub\Model\Customer\Repository
 */
class Db extends RepositoryAbstract implements Repository
{
    /**
     * @param array $filters
     * @return \B2W\SkyHub\Contracts\Resource\Collection|void
     */
    public function all($filters = array())
    {
        // TODO: Implement all() method.
    }

    /**
     * @param $order
     * @return Entity|mixed
     * @throws CustomerInstance
     */
    public function one($order)
    {
        if (!$order instanceof \B2W\SkyHub\Model\Sales\Order\Entity) {
            throw new CustomerInstance();
        }

        $customerId = get_post_meta($order->getId(), '_customer_user', true);

        $customer = $this->emptyOne();
        $customer->setId($customerId);
        Customer::convert($customer);
        \B2W\SkyHub\Model\Transformer\Sales\Order\Customer::convert($order, $customer);

        return $customer;
    }

    /**
     * @return Entity|mixed
     */
    public function emptyOne()
    {
        return new Entity();
    }

    /**
     * @return \B2W\SkyHub\Contracts\Resource\Collection|Collection
     */
    public function emptyCollection()
    {
        return new Collection();
    }
}
