<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model;

class Service
{

    /**
     * @var \SkyHub\Api
     */
    protected $api = null;

    public function __construct()
    {
        $this->initApi();
    }

    public function api()
    {
        if (is_null($this->api)) {
            $this->initApi();
        }

        return $this->api;
    }

    public function initApi()
    {
        $service = null;

        $this->api = new \SkyHub\Api(
            'testemodulo@skyhub.com.br',
            'k28PJT7_upjVJbjuPBpD',
            'bZa6Ml0zgS'
        );

        /** TODO LOGS */
        /*
        if ($this->isLogEnabled()) {
            $logFileName = $this->getLogFilename();
            $logFilePath = Mage::app()->getConfig()->getOptions()->getLogDir();

            $this->apiService()
                ->setLogAllowed(true)
                ->setLogFileName($logFileName)
                ->setLogFilePath($logFilePath);
        }
        */

        return $this;
    }
}
