<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\Skyhub\Contracts;

use B2W\Skyhub\Contracts\Data\Collection;

interface Factory
{
    /** Returns all itens (filtered or not)
     * @param array $filter
     * @return Collection $collection
     */
    public static function all($filter = array());

    /**
     * Return single order filtered by id
     *
     * @param $id
     * @return \B2W\Skyhub\Contracts\Data\Entity $entity
     */
    public static function one($id);
}
