<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Contract\Resource;

/**
 * Interface CollectionInterface
 * @package B2W\SkyHub\Contract\Resource
 */
interface CollectionInterface extends \Iterator
{
    /**
     * @return mixed
     */
    public function addItem($item);

    /**
     * @param $key
     * @param $value
     * @return mixed
     */
    public function getItemByKey($key, $value);
}
