<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Transformer\Sales\Order\Address;

use B2W\SkyHub\Model\Map\Attribute;
use B2W\SkyHub\Model\Sales\Order\Address\Entity;
use B2W\SkyHub\Model\Map\Sales\Order\Address\Map;
use B2W\SkyHub\Model\Transformer\ApiToEntityAbstract;
use B2W\SkyHub\Model\Transformer\PostToEntityAbstract;

/**
 * Class PostToEntity
 * @package B2W\SkyHub\Model\Transformer\Sales\Order\Address
 */
class ApiToEntity extends ApiToEntityAbstract
{
    /**
     * @return Map|mixed
     */
    protected function _getMapInstance()
    {
        return new Map();
    }

    /**
     * @return Entity|null
     */
    public function _getEntityInstance()
    {
        $entity = new Entity();
        $entity->setType($this->_getAddrType());
        return $entity;
    }

    /**
     * @return string
     */
    protected function _getAddrType()
    {
        return $this->_attribute->getSkyhub() == 'billing_address'
            ? 'billing'
            : 'shipping';
    }

    /**
     * @param $attribute
     * @return mixed|null
     */
    protected function _getApiValue(Attribute $attribute, array $data)
    {
        $local = str_replace('{{ADDR_TYPE}}', '_' . $this->_getAddrType(), $attribute->getWordpress());
        $attribute->setWordpress($local);
        return parent::_getApiValue($attribute, $data);
    }
}
