<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Transformer\Sales\Order\Address;

use B2W\SkyHub\Helper\App;
use B2W\SkyHub\Model\Sales\Order\Address\Entity;
use B2W\SkyHub\Model\Sales\Order\Address\Map;
use B2W\SkyHub\Model\TransformerAbstract;

/**
 * Class Post
 * @package B2W\SkyHub\Model\Transformer\Sales\Order\Address
 */
class Post extends TransformerAbstract
{
    /**
     * @param Entity $address
     * @return mixed
     */
    static public function convert($address)
    {
        /** @var  $instance */
        $instance = static::_instantiate();
        return $instance->_convert($address);
    }

    /**
     * @param Entity $address
     * @return array
     * @throws \B2W\SkyHub\Exception\Helper\HelperNotFound
     */
    protected function _convert(Entity $address)
    {
        $return = array();
        $map    = new Map();
        /** @var App $helper */
        $helper = \App::helper('app');

        foreach ($map->map() as $attr) {

            if (empty($attr['local'])) {
                continue;
            }

            $method = $helper->getGetterMethodName($address, $attr['skyhub']);
            $key    = '_' . str_replace('{{ADDR_TYPE}}', $address->getType(), $attr['local']);
            $value  = $address->$method();

            if (is_array($value)) {
                $value = current($value);
            }

            $return['meta_input'][$key] = $value;
        }

        return $return;
    }
}
