<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

class App
{
    /**
     * App constructor.
     * @throws Exception
     */
    public function __construct()
    {
        spl_autoload_register(function($className) {

            if (class_exists($className)) {
                return $this;
            }

            $file   = str_replace('\\', DIRECTORY_SEPARATOR, $className) . '.php';
            $path   = __DIR__ . DIRECTORY_SEPARATOR . $file;

            if (file_exists($path)) {
                require_once($path);
            }
        });

        $this->_init();

        return $this;
    }


    protected function _init()
    {
//        $this->_testAttributes();
//        $this->_testCategories();
//        $this->_testCategory();
//        $this->_testProducts();
        $this->_testSingleProduct();
    }

    protected function _testSingleProduct()
    {
        $repo       = \B2W\Skyhub\Model\Catalog\Product\Factory::create();
        $product    = $repo::one(17);

        $product->getVariations();
        $product->getCategories();
        $product->getVariationAttributes();
        $product->getSpecifications();

        echo '<pre>';
        print_r($product);


        foreach ($product->getVariations() as $variation) {
            print_r($variation->getSpecifications());
        }

        echo '</pre>';
    }

    protected function _testProducts()
    {
        $repo       = \B2W\Skyhub\Model\Catalog\Product\Factory::create();
        $products   = $repo::all();

        echo '<Pre>';

        foreach ($products as $product) {
            print_r($product);
        }

        echo '</Pre>';

        echo '<br /><br />';
    }

    protected function _testCategory()
    {
        $repo       = \B2W\Skyhub\Model\Catalog\Category\Factory::create();
        $category   = $repo::one(21);

        echo '<pre>';
        print_r($category);
        echo '</pre>';
    }

    protected function _testCategories()
    {
        $repo       = \B2W\Skyhub\Model\Catalog\Category\Factory::create();
        $categories = $repo::all();

        foreach ($categories as $category) {
            echo $category->getName() . "<br />";

            if ($category->getParent()) {
                echo $category->getParent()->getName() . '<br />';
            }

            echo '<br />';
        }

        echo '<br /><br />';
    }


    protected function _testAttributes()
    {
        $repository = \B2W\Skyhub\Model\Catalog\Product\Attribute\Factory::create();

        echo '<pre>';
        $attrs = $repository::all();

        foreach ($attrs as $attr) {
            echo $attr->getLabel() . "<br />";
            foreach ($attr->getOptions() as $option) {
                echo $option->getCode() . "<br />";
            }
            echo '<br /><br />';
        }

        echo '</pre>';
    }
}
