<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Transformer\Post\Catalog;

use B2W\SkyHub\Model\Catalog\Product\Attribute\Map;
use B2W\SkyHub\Model\Transformer\PostAbstract;

/**
 * Class Product
 * @package B2W\SkyHub\Model\Transformer\Post\Catalog
 */
class Product extends PostAbstract
{
    /**
     * @return $this|mixed
     */
    protected function _init()
    {
        $map = new Map();

        $this->_addMap('ID', 'id');

        foreach ($map->map() as $item) {
            $this->_addMap($item['local'], $item['skyhub']);
        }

        return $this;
    }
}
