<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Resource\Sales\Order\Status\Repository;


use B2W\SkyHub\Model\Resource\RepositoryAbstract;

class Api extends RepositoryAbstract
{
    public function all()
    {
        $requestHandler = \App::api()->orderStatus();
        $response       = $requestHandler->statuses();

        if ($response->exception()) {
            /** @var \SkyHub\Api\Handler\Response\HandlerException $response */
            throw new \Exception($response->message());
        }

        /** @var \SkyHub\Api\Handler\Response\HandlerDefault $response */
        if (!$response->body()) {
            return false;
        }

        return $response;
    }
}
