<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Contracts\Sales\Order\Shipment;


/**
 * Interface Entity
 * @package B2W\SkyHub\Contracts\Sales\Order\Shipment
 */
interface Entity
{
    /**
     * @return string
     */
    public function getCode();

    /**
     * @param $code
     * @return string
     */
    public function setCode($code);

    /**
     * @return \B2W\Skyhub\Model\Sales\Order\Shipment\Item\Collection
     */
    public function getItems();

    /**
     * @param \B2W\Skyhub\Model\Sales\Order\Shipment\Item\Collection $items
     * @return mixed
     */
    public function setItems(\B2W\Skyhub\Model\Sales\Order\Shipment\Item\Collection $items);

    /**
     * @return \B2W\Skyhub\Model\Sales\Order\Shipment\Track\Collection
     */
    public function getTracks();

    /**
     * @param \B2W\Skyhub\Model\Sales\Order\Shipment\Track\Collection $tracks
     * @return mixed
     */
    public function setTracks(\B2W\Skyhub\Model\Sales\Order\Shipment\Track\Collection $tracks);
}
