<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\View\Admin\Attribute;

use B2W\SkyHub\View\Template;

/**
 * Class FieldAbstract
 * @package B2W\SkyHub\View\Admin\Attribute
 */
class FieldAbstract extends Template
{
    /**
     * @var null
     */
    protected $_value   = null;
    /**
     * @var null
     */
    protected $_note    = array();

    /**
     * @param string $value
     * @return $this
     */
    public function setValue($value)
    {
        $this->_value = $value;
        return $this;
    }

    /**
     * @return string
     */
    public function getValue()
    {
        return $this->_value;
    }

    /**
     * @param string  $note
     * @return $this
     */
    public function addNote($note)
    {
        $this->_note[] = $note;
        return $this;
    }

    /**
     * @return string
     */
    public function getNote()
    {
        return implode('<br />', $this->_note);
    }
}
