<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\Skyhub\Model\Data;

use B2W\Skyhub\Contracts\Data\Collection;

/**
 * Class CollectionAbstract
 * @package B2W\Skyhub\Data
 */
abstract class CollectionAbstract implements Collection
{
    /**
     * @var array
     */
    protected $_items       = array();
    /**
     * @var int
     */
    protected $_position    = 0;

    /**
     * @param $item
     * @return $this|mixed
     */
    public function addItem($item)
    {
        $this->_items[] = $item;
        return $this;
    }

    /**
     * @return mixed
     */
    public function current()
    {
        return $this->_items[$this->_position];
    }

    /**
     * @return void
     */
    public function next()
    {
        ++$this->_position;
    }

    /**
     * @return int|mixed
     */
    public function key()
    {
        return $this->_position;
    }

    /**
     * @return bool
     */
    public function valid()
    {
        return isset($this->_items[$this->_position]);
    }

    /**
     * @return void
     */
    public function rewind()
    {
        $this->_position = 0;
    }
}
