<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\Skyhub\Model\Data;


/**
 * Class RepositoryAbstract
 * @package B2W\Skyhub\Model\Data
 */
class RepositoryAbstract
{
    /**
     * @return RepositoryAbstract|bool
     */
    public static function instantiate()
    {
        static $instance = false;
        if ($instance === false) {
            $instance = new static();
        }

        return $instance;
    }

    /**
     * EntityAbstract constructor.
     */
    private function __construct()
    {
        return $this;
    }


    /**
     * @return $this
     */
    private function __clone()
    {
        return $this;
    }
}
