<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\Skyhub\Contracts\Catalog\Product\Specification;

/**
 * Interface Entity
 * @package B2W\Skyhub\Contracts\Catalog\Product\Specification
 */
interface Entity
{
    /**
     * @param \B2W\Skyhub\Contracts\Catalog\Product\Attribute\Entity $attribute
     * @return mixed
     */
    public function setAttribute(\B2W\Skyhub\Contracts\Catalog\Product\Attribute\Entity $attribute);

    /**
     * @return \B2W\Skyhub\Contracts\Catalog\Product\Attribute\Entity
     */
    public function getAttribute();

    /**
     * @param $value
     * @return mixed
     */
    public function setValue($value);

    /**
     * @return mixed
     */
    public function getValue();
}
