<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\Skyhub\Model\Catalog\Product\Attribute;


/**
 * Class Map
 * @package B2W\Skyhub\Model\Catalog\Product\Attribute
 */
class Map
{
    const OPTION    = 'b2w_skyhub_product_attributes';
    protected $_map = null;

    /**
     * @return array
     */
    public function map()
    {
        if (is_null($this->_map)) {
            $options = get_option(self::OPTION, null);

            if (is_null($options)) {
                $options = serialize($this->_createDefaultAttributeMap());
                add_option(self::OPTION, $options);
            }

            $this->_map = unserialize($options);
        }

        return $this->_map;
    }

    /**
     * @param $skyhubAttributeCode
     * @return bool|string
     */
    public function attribute($skyhubAttributeCode)
    {
        $map = $this->map();

        foreach ($map as $attribute) {
            if ($attribute['skyhub'] == $skyhubAttributeCode) {
                return $attribute['local'];
            }
        }

        return false;
    }

    /**
     * @return array
     */
    private function _createDefaultAttributeMap()
    {
        $config = \App::getConfig('catalog/product/attribute/skyhub');
        $map = array();
        foreach ($config as $attribute) {

            if (!isset($attribute['default_local']) || empty($attribute['default_local'])) {
                continue;
            }

            $map[$attribute['code']] = array(
                'skyhub'    => $attribute['code'],
                'local'     => $attribute['default_local']
            );
        }

        return $map;
    }
}
