<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Transformer\Order\Shipment;

use B2W\SkyHub\Model\Entity\Order\ShipmentEntity;
use B2W\SkyHub\Model\Map\Order\ShipmentMap;

class ApiToEntity extends \B2W\SkyHub\Model\Transformer\ApiToEntityAbstract
{
    protected function _getEntityInstance()
    {
        return new ShipmentEntity();
    }

    protected function _getMapInstance()
    {
        return new ShipmentMap();
    }

    protected function _prepareData($data = null)
    {
        $data = current($this->_response);
        return parent::_prepareData($data);
    }
}
