<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Contracts\Resource;

/**
 * Interface Repository
 * @package B2W\SkyHub\Contracts\Resource
 */
interface Repository
{
    /**
     * @param array $filters
     * @return \B2W\SkyHub\Contracts\Resource\Collection
     */
    public function all($filters = array());

    /**
     * @param $id
     * @return mixed
     */
    public function one($id);
}
