<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Transformer\Sales\Order\Invoice;

use B2W\SkyHub\Model\Map\Sales\Order\Invoice\Map;
use B2W\SkyHub\Model\Resource\Sales\Order\Invoice\Collection;
use B2W\SkyHub\Model\Sales\Order\Invoice\Entity;
use B2W\SkyHub\Model\Transformer\ApiToEntityAbstract;

class ApiToEntity extends ApiToEntityAbstract
{
    /**
     * @return Entity|mixed
     */
    protected function _getEntityInstance()
    {
        return new Entity();
    }

    /**
     * @return Map|mixed
     */
    protected function _getMapInstance()
    {
        return new Map();
    }

    public function convert()
    {
        $collection = new Collection();
        $data       = $this->_response->toArray();

        if (!isset($data['invoices'])) {
            return null;
        }

        foreach ($data['invoices'] as $invoice) {
            $this->_entity      = new Entity();
            $this->_response    = $invoice;
            $collection->addItem(parent::convert());
        }

        return $collection;
    }
}
