<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Transformer\Sales\Order\Invoice;

use B2W\SkyHub\Model\Map\Attribute;
use B2W\SkyHub\Model\Map\Sales\Order\Invoice\Map;
use B2W\SkyHub\Model\Transformer\EntityToDbAbstract;

/** @method \B2W\SkyHub\Model\Sales\Order\Entity getEntity() */
class EntityToDb extends EntityToDbAbstract
{
    /**
     * @return Map|mixed
     */
    protected function _getMapInstance()
    {
        return new Map();
    }

    /**
     * @param Attribute $attribute
     * @return string
     * @throws \B2W\SkyHub\Exception\Helper\HelperNotFound
     */
    protected function _getEntityValue(Attribute $attribute)
    {
        $entity = $this->getEntity()->getInvoices()->first();
        $method = $this->_helper()->getGetterMethodName($entity, $attribute->getSkyhub());

        if (!$method) {
            return '';
        }

        return $entity->$method();
    }
}
