<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Transformer\Sales\Order\Post;

use B2W\SkyHub\Contracts\Sales\Order\Entity;
use B2W\SkyHub\Model\TransformerAbstract;

/**
 * Class Cnpj
 * @package B2W\SkyHub\Model\Transformer\Sales\Order\Post
 */
class Constant extends TransformerAbstract
{
    /**
     * @param Entity $order
     * @return mixed
     */
    static public function convert(Entity $order)
    {
        /** @var  $instance */
        $instance = static::_instantiate();
        return $instance->_convert($order);
    }

    /**
     * @param Entity $order
     * @return array
     */
    protected function _convert(Entity $order)
    {
        return array(
            'meta_input'    => array(
                '_cart_discount'                => 0,
                '_cart_discount_tax'            => 0,
                '_cart_hash'                    => 0,
                '_completed_date'               => 0,
                '_created_via'                  => 'skyhub',
                '_customer_ip_address'          => '',
                '_customer_user'                => '',
                '_customer_user_agent'          => '',
                '_date_completed'               => '',
                '_date_paid'                    => '',
                '_order_currency'               => 'BRL',
                '_order_shipping_tax'           => 0,
                '_order_stock_reduced'          => 'no',
                '_order_tax'                    => 0,
                '_order_version'                => '',
                '_paid_date'                    => '',
                '_payment_method'               => '',
                '_payment_method_title'         => '',
                '_prices_include_tax'           => 0,
                '_recorded_coupon_usage_counts' => 'no',
                '_recorded_sales'               => 'yes',
                '_shipping_company'             => '',
                '_transaction_id'               => '',
                '_transaction_id'               => ''
            )
        );
    }
}
