<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Transformer\Sales\Order\Post;

use B2W\SkyHub\Contracts\Sales\Order\Address\Entity;
use B2W\SkyHub\Model\TransformerAbstract;

class LastName extends TransformerAbstract
{
    static public function convert(Entity $address)
    {
        /** @var  $instance */
        $instance = static::_instantiate();
        return $instance->_convert($address);
    }

    protected function _convert(Entity $address)
    {
        $result     = array();
        $name       = explode(' ', $address->getAdditionalData('name'));
        $nameCount  = count($name);
        $counter    = ceil($nameCount / 2);

        for ($i = $counter; $i < $nameCount; $i ++) {
            $result[] = $name[$i];
        }

        return array(
            'meta_input'    => array(
                '_' . $address->getType() . '_last_name'   => implode(' ', $result)
            )
        );
    }
}
