<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\Skyhub\Model\Catalog\Product\Variation\Converter\Post;

use B2W\Skyhub\Model\Data\Converter\Post\EntityAbstract;

/**
 * Class Entity
 * @package B2W\Skyhub\Contracts\Catalog\Product\Converter\Post
 */
class Entity extends EntityAbstract
{
    /**
     * @return $this|mixed
     * @throws \Exception
     */
    protected function _init()
    {
        $map    = array(
            'ID'            => 'id',
            '_sku'          => 'sku',
            '_stock'        => 'qty',
            '_price'        => 'price'
        );

        foreach ($map as $post => $entity) {
            $this->_addMap($post, $entity);
        }

        return $this;
    }
}
