<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Contracts\Resource\Sales\Order\Customer;

use B2W\SkyHub\Contracts\Sales\Order\Customer\Entity;

/**
 * Interface Repository
 * @package B2W\SkyHub\Contracts\Resource\Sales\Order\Customer
 */
interface Repository
{
    /**
     * @param \B2W\SkyHub\Contracts\Sales\Order\Entity|\WP_Post $order
     * @return Entity
     */
    public function load($order);

    /**
     * @param $cpf
     * @return Entity
     */
    public function cpf($cpf);

    /**
     * @param $cnpj
     * @return Entity
     */
    public function cnpj($cnpj);

    /**
     * @param integer
     * @return Entity
     */
    public function one($id);
}
