<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\Skyhub\Model\Catalog\Category;

/**
 * Class Entity
 * @package B2W\Skyhub\Model\Catalog\Product
 */
class Entity implements \B2W\Skyhub\Contracts\Catalog\Category\Entity
{
    protected $_id      = null;
    protected $_code    = null;
    protected $_name    = null;
    protected $_parent  = null;

    /**
     * @return null
     */
    public function getId()
    {
        return $this->_id;
    }

    /**
     * @param $id
     * @return $this|mixed
     */
    public function setId($id)
    {
        $this->_id = $id;
        return $this;
    }

    /**
     * @return null
     */
    public function getCode()
    {
        return $this->_code;
    }

    /**
     * @param $code
     * @return $this|mixed
     */
    public function setCode($code)
    {
        $this->_code = $code;
        return $this;
    }

    /**
     * @return null
     */
    public function getName()
    {
        return $this->_name;
    }

    /**
     * @param $name
     * @return $this|mixed
     */
    public function setName($name)
    {
        $this->_name = $name;
        return $this;
    }

    public function getParent()
    {
        return $this->_parent;
    }

    public function setParent(\B2W\Skyhub\Contracts\Catalog\Category\Entity $parent)
    {
        $this->_parent = $parent;
        return $this;
    }

    public function getChilds()
    {
        // TODO: Implement getChilds() method.
    }
}
