<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\Skyhub\Model\Catalog\Category;

use B2W\Skyhub\Model\Data\Repository\FactoryAbstract;

/**
 * Class Factory
 * @package B2W\Skyhub\Model\Catalog\Category
 */
class Factory extends FactoryAbstract implements \B2W\Skyhub\Contracts\Data\Factory
{
    /**
     * @param null $repositoryType
     * @return Repository\Db
     * @throws \Exception
     */
    public static function create($repositoryType = null)
    {
        return self::instantiate('\B2W\Skyhub\Model\Catalog\Category\Repository\\', $repositoryType);
    }
}
