<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Transformer\Catalog\Product\Specification;

use B2W\SkyHub\Model\Catalog\Product\Specification\Entity;
use B2W\SkyHub\Model\Catalog\Product\Specification\Collection;

class EntityToApi
{
    public function convert(Collection $collection, $parentTranformer)
    {
        /** @var \SkyHub\Api\EntityInterface\Catalog\Product $productInterface */
        $productInterface   = $parentTranformer->getInterface();

        /** @var Entity $specification */
        foreach ($collection as $specification) {
            $productInterface->addSpecification(
                $specification->getAttribute()->getCode(),
                $specification->getOption()->getLabel()
            );
        }

        return null;
    }
}
