<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\Skyhub\Model\Catalog\Product\Variation\Repository;

use B2W\Skyhub\Exception\Catalog\Product\Variation\HasNoParentException;
use B2W\Skyhub\Model\Catalog\Product\Variation\Entity;
use B2W\Skyhub\Model\Catalog\Product\Variation\Collection;

/**
 * Class Db
 * @package B2W\Skyhub\Model\Order\Repository
 */
class Db implements \B2W\Skyhub\Contracts\Data\Repository
{
    /**
     * @param array $filters
     * @return \B2W\Skyhub\Contracts\Data\Collection|Collection
     * @throws \Exception
     */
    public static function all($filters = array())
    {
        if (!isset($filters['post_parent'])) {
            throw new HasNoParentException();
        }

        $defaultFilter = array(
            'post_status'   => array('publish'),
            'post_type'     => Entity::POST_TYPE,
        );

        if (!empty($filters)) {
            foreach ($filters as $key => $value) {
                $defaultFilter[$key] = $value;
            }
        }

        $posts = get_posts($defaultFilter);

        $collection = new Collection();

        foreach ($posts as $post) {
            $variation = self::one($post);
            $collection->addItem($variation);
        }

        return $collection;
    }

    /**
     * @param $id
     * @return Entity
     * @throws \Exception
     */
    public static function one($id)
    {
        if ($id instanceof \WP_Post) {
            $post = $id;
        } else {
            $post = get_post($id);
        }

        $variation = self::emptyOne();
        \B2W\Skyhub\Model\Catalog\Product\Variation\Converter\Post\Entity::convert($post, $variation);

        return $variation;
    }

    /**
     * @return Entity|mixed
     */
    public static function emptyOne()
    {
        return new Entity();
    }

    /**
     * @return \B2W\Skyhub\Contracts\Data\Collection|Collection
     */
    public static function emptyCollection()
    {
        return new Collection();
    }
}
