<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Catalog\Product\Variation\Repository;

use B2W\SkyHub\Exception\Catalog\Product\Variation\HasNoParentException;
use B2W\SkyHub\Model\Catalog\Product\Variation\Entity;
use B2W\SkyHub\Model\Catalog\Product\Variation\Collection;
use B2W\SkyHub\Model\Resource\RepositoryAbstract;

/**
 * Class Db
 * @package B2W\SkyHub\Model\Order\Repository
 */
class Db extends RepositoryAbstract implements \B2W\SkyHub\Contracts\Resource\Repository
{
    /**
     * @param array $filters
     * @return \B2W\SkyHub\Contracts\Resource\Collection|Collection
     * @throws \Exception
     */
    public function all($filters = array())
    {
        if (!isset($filters['post_parent'])) {
            throw new HasNoParentException();
        }

        $defaultFilter = array(
            'post_status'   => array('publish'),
            'post_type'     => Entity::POST_TYPE,
        );

        if (!empty($filters)) {
            foreach ($filters as $key => $value) {
                $defaultFilter[$key] = $value;
            }
        }

        $posts = get_posts($defaultFilter);

        $collection = new Collection();

        foreach ($posts as $post) {
            $variation = $this->one($post);
            $collection->addItem($variation);
        }

        return $collection;
    }

    /**
     * @param $id
     * @return mixed|null
     * @throws \Exception
     */
    public function one($id)
    {
        if ($id instanceof \WP_Post) {
            $post = $id;
        } else {
            $post = get_post($id);
        }

        $transformer = new \B2W\SkyHub\Model\Transformer\Catalog\Product\Variation\PostToEntity();
        $transformer->setPost($post);
        return $transformer->convert();
    }
}
