<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Transformer\Sales\Order\Customer\Misc;

use B2W\SkyHub\Model\Transformer\PostToEntityAbstract;

class NamePostToEntity extends PostToEntityAbstract
{
    protected function _getAttributeMap()
    {
        return array();
    }

    public function convert()
    {
        $this->_parentEntity->setName(current($this->_meta['first_name']) . ' ' . current($this->_meta['last_name']));
        return null;
    }
}
