<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Transformer\Catalog\Product\Image;

use B2W\SkyHub\Model\Catalog\Product\Entity;
use B2W\SkyHub\Model\Transformer\PostToEntityAbstract;

/**
 * Class PostToEntity
 * @package B2W\SkyHub\Model\Transformer\Catalog\Product\Image
 */
class PostToEntity extends PostToEntityAbstract
{
    /**
     * @return array|mixed
     */
    protected function _getAttributeMap()
    {
        return array();
    }

    /**
     * @return array|null
     */
    public function convert()
    {
        $ids    = array();
        $images = array();

        //
        if (isset($this->_meta[Entity::META_IMAGE])) {
            $ids[] = current($this->_meta[Entity::META_IMAGE]);
        }

        //IMAGE GALLERY
        $galleryIds = get_post_meta($this->_post->ID, Entity::META_GALLERY, true);
        if ($galleryIds) {
            $ids = array_unique(array_merge($ids, explode(',', $galleryIds)));
        }

        foreach ($ids as $id) {
            $id         = trim($id);
            $imagePost  = get_post($id);

            if ($imagePost->guid) {
                $images[] = $imagePost->guid;
            }
        }

        return $images;
    }
}
