<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Transformer\Catalog\Product\Category;

use \B2W\SkyHub\Model\Resource\Catalog\Category\Collection;
use B2W\SkyHub\Model\Catalog\Category\Entity;

/**
 * Class PostToEntity
 * @package B2W\SkyHub\Model\Transformer\Catalog\Product\Category
 */
class EntityToApi
{
    public function convert(Collection $collection, $parentTranformer)
    {
        /** @var \SkyHub\Api\EntityInterface\Catalog\Product $productInterface */
        $productInterface   = $parentTranformer->getInterface();

        /** @var Entity $category */
        foreach ($collection as $category) {
            $productInterface->addCategory($category->getCode(), $category->getName());
        }

        return null;
    }
}
