<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Map;


/**
 * Class MapAbstract
 * @package B2W\SkyHub\Model
 */
abstract class MapAbstract
{
    /**
     * @var null
     */
    protected $_map     = null;

    /**
     * @return string
     */
    abstract protected function _getConfigPath();

    /**
     * @return string
     */
    abstract protected function _getOptionsName();

    /**
     * @return array
     */
    public function map()
    {
        if (is_null($this->_map)) {
            $options = $this->_getOptions();

            if (!$options) {
                $options = serialize($this->_createDefaultAttributeMap());
                $this->_addOption($options);
            }

            $this->_map = unserialize($options);
        }

        return $this->_map;
    }

    /**
     * @return mixed|null
     */
    protected function _getOptions()
    {
        if (!$this->_getOptionsName()) {
            return null;
        }

        return get_option($this->_getOptionsName(), null);
    }

    /**
     * @param $options
     * @return bool|null
     */
    protected function _addOption($options)
    {
        if (!$this->_getOptionsName()) {
            return null;
        }

        return add_option($this->_getOptionsName(), $options);
    }

    /**
     * @param $skyhubCode
     * @return bool|string
     */
    public function attribute($skyhubCode)
    {
        $map = $this->map();

        foreach ($map as $attribute) {
            if ($attribute['skyhub'] == $skyhubCode) {
                return $this->_prepareString($attribute['wordpress']);
            }
        }

        return false;
    }

    /**
     * @param $attr
     * @param $related
     * @return bool
     */
    public function setRelated($attr, $related)
    {
        $map = $this->map();

        if (!isset($map[$attr])) {
            return false;
        }

        if (strpos($related, '+') !== false) {
            $related = explode('+', $related);
            $related = array_map(function($v) {
                return trim($v);
            }, $related);
        }

        $map[$attr]['wordpress'] = $related;

        $this->_map = $map;

        return true;
    }

    /**
     * @return $this
     */
    public function save()
    {
        $map = $this->map();

        if ($this->_getOptionsName()) {
            update_option($this->_getOptionsName(), serialize($map));
        }

        return $this;
    }

    /**
     * @return array
     */
    private function _createDefaultAttributeMap()
    {
        $config = \App::config($this->_getConfigPath());
        $map = array();
        foreach ($config as $attribute) {

            $map[] = array(
                'skyhub'    => isset($attribute['skyhub']) ? $attribute['skyhub'] : null,
                'wordpress' => isset($attribute['wordpress']) ? $attribute['wordpress'] : '',
                'mapper'    => isset($attribute['mapper']) ? $attribute['mapper'] : null
            );
        }

        return $map;
    }

    /**
     * @param $value
     * @return string
     */
    protected function _prepareString($value)
    {
        if (is_array($value)) {
            return implode(' + ', $value);
        }

        return $value;
    }
}
