<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Resource\Sales\Order\Customer\Repository;

use B2W\SkyHub\Contracts\Resource\Sales\Order\Customer\Repository;
use B2W\SkyHub\Model\Resource\RepositoryAbstract;
use B2W\SkyHub\Model\Resource\Select;
use B2W\SkyHub\Model\Sales\Order\Customer\Entity;
use B2W\SkyHub\Model\Transformer\Sales\Order\Customer\PostToEntity;

/**
 * Class Db
 * @package B2W\SkyHub\Model\Customer\Repository
 */
class Db extends RepositoryAbstract implements Repository
{
    /**
     * @param \B2W\SkyHub\Contracts\Sales\Order\Entity|\WP_Post $order
     * @return \B2W\SkyHub\Model\Sales\Order\Customer\Entity|mixed
     * @throws \Exception
     */
    public function load($order)
    {
        $post           = $order instanceof \WP_Post ? $order : get_post($order->getId());
        $customer       = new \B2W\SkyHub\Model\Sales\Order\Customer\Entity();
        $transformer    = \App::transformer('sales/order/customer/post_to_entity');
        $transformer->convert($post, $customer);

        return $customer;
    }

    /**
     * @param $cpf
     * @return Entity
     */
    public function cpf($cpf)
    {
        global $wpdb;

        $select = new Select();
        $select->column('user_id');
        $select->from('usermeta');
        $select->where("meta_key = 'billing_cpf'");
        $select->where("REPLACE(REPLACE(meta_value, '.', ''), '-', '') = '$cpf'");

        foreach ($wpdb->get_results($select) as $customer) {
            return $this->one($customer->user_id);
        }

        return new Entity();
    }

    /**
     * @param $cnpj
     * @return Entity
     */
    public function cnpj($cnpj)
    {
        global $wpdb;

        $select = new Select();
        $select->column('user_id');
        $select->from('usermeta');
        $select->where("meta_key = 'billing_cnpj'");
        $select->where("REPLACE(REPLACE(meta_value, '.', ''), '-', '') = '$cnpj'");

        foreach ($wpdb->get_results($select) as $customer) {
            return $this->one($customer->user_id);
        }

        return new Entity();
    }

    public function one($id)
    {
        $user       = get_user_by('id', $id);
        $meta       = get_user_meta($id);

        /** @var PostToEntity $transformer */
        $transformer = \App::transformer('sales/order/customer/post_to_entity');
        $transformer->setPost($user);
        $transformer->setMeta($meta);

        return $transformer->convert();
    }
}
