<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Validation\Sales\Order;

/**
 * Class Entity
 * @package B2W\SkyHub\Model\Validation\Sales\Order
 */
class Entity
{
    /**
     * @param \B2W\SkyHub\Contracts\Sales\Order\Entity $order
     * @throws \Exception
     */
    public function validate(\B2W\SkyHub\Contracts\Sales\Order\Entity $order)
    {
        if (!$order->getCode()) {
            throw new \Exception('Order must have code');
        }

        if ($order->getItems()->size() <= 0) {
            throw new \Exception('Order must have items');
        }
    }
}
