<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Sales\Order;

/**
 * Class Map
 * @package B2W\SkyHub\Model\Sales\Order
 */
class Map
{
    /**
     * @var null
     */
    protected $_map = array();

    /**
     * Map constructor.
     */
    public function __construct()
    {
        foreach (\App::config('map/sales/order') as $key => $attribute) {
            $this->addMap(
                isset($attribute['code']) ? $attribute['code'] : null,
                isset($attribute['default_local']) ? $attribute['default_local'] : null,
                isset($attribute['mapper']) ? $attribute['mapper'] : null
            );
        }
    }

    /**
     * @return array|null
     */
    public function map()
    {
        return $this->_map;
    }

    /**
     * @param $skyhub
     * @param $local
     * @param null $mapper
     * @return $this
     */
    public function addMap($skyhub, $local, $mapper = null)
    {
        if (empty($local) && empty($mapper)) {
            return $this;
        }

        $this->_map[] = array(
            'skyhub'    => $skyhub,
            'local'     => $local,
            'mapper'    => $mapper
        );

        return $this;
    }
}
