<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Queue\Worker;

/**
 * Class OrderUpdateWorker
 * @package B2W\SkyHub\Model\Queue\Worker
 */
class OrderUpdateWorker
{
    /**
     * @param $orderId
     * @return $this
     * @throws \B2W\SkyHub\Exception\Data\RepositoryNotFound
     */
    public function shipp($orderId)
    {
        $order = $this->_getOrder($orderId);
        if (!$order->getChannel()) {
            return $this;
        }
        \App::apiRepository(\App::REPOSITORY_ORDER)->shipp($order);
        return $this;
    }

    /**
     * @param $orderId
     * @return $this
     * @throws \B2W\SkyHub\Exception\Data\RepositoryNotFound
     */
    public function invoice($orderId)
    {
        $order = $this->_getOrder($orderId);
        if (!$order->getChannel()) {
            return $this;
        }
        \App::apiRepository(\App::REPOSITORY_ORDER)->invoiceApi($order);
        return $this;
    }

    /**
     * @param $orderId
     * @return $this
     * @throws \B2W\SkyHub\Exception\Data\RepositoryNotFound
     */
    public function delivery($orderId)
    {
        $order = $this->_getOrder($orderId);
        if (!$order->getChannel()) {
            return $this;
        }
        \App::apiRepository(\App::REPOSITORY_ORDER)->delivery($order);
        return $this;
    }

    /**
     * @param $orderId
     * @return $this
     * @throws \B2W\SkyHub\Exception\Data\RepositoryNotFound
     */
    public function cancel($orderId)
    {
        $order = $this->_getOrder($orderId);
        if (!$order->getChannel()) {
            return $this;
        }
        \App::apiRepository(\App::REPOSITORY_ORDER)->cancel($order);
        return $this;
    }

    /**
     * @param $orderId
     * @return mixed
     * @throws \B2W\SkyHub\Exception\Data\RepositoryNotFound
     */
    protected function _getOrder($orderId)
    {
        return \App::repository(\App::REPOSITORY_ORDER)->one($orderId);;
    }
}
