<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Queue\Worker;

use B2W\SkyHub\Model\Queue\Message\OrderUpdateMessage;

/**
 * Class OrderUpdateWorker
 * @package B2W\SkyHub\Model\Queue\Worker
 */
class OrderUpdateWorker
{
    /**
     * @param $orderId
     * @throws \B2W\SkyHub\Exception\Data\RepositoryNotFound
     * @throws \B2W\SkyHub\Exception\Exception
     * @throws \B2W\SkyHub\Exception\Helper\HelperNotFound
     */
    public function run($orderId)
    {
        $order = $this->_getOrder($orderId);
        $apiOrder   = \App::apiRepository(\App::REPOSITORY_ORDER)->one($order->getCode());

        $apiOrder->save();

        if (!\App::helper('order')->isComplete($apiOrder)) {
            $message = new OrderUpdateMessage($apiOrder->getId());
            \App::repository(\App::REPOSITORY_QUEUE)->add($message);
        }
    }

    /**
     * @param $orderId
     * @return $this
     * @throws \B2W\SkyHub\Exception\Data\RepositoryNotFound
     */
    public function shipp($orderId)
    {
        $order = $this->_getOrder($orderId);
        \App::apiRepository(\App::REPOSITORY_ORDER)->shipp($order);
        return $this;
    }

    /**
     * @param $orderId
     * @return mixed
     * @throws \B2W\SkyHub\Exception\Data\RepositoryNotFound
     */
    protected function _getOrder($orderId)
    {
        return \App::repository(\App::REPOSITORY_ORDER)->one($orderId);;
    }
}
