<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Queue\Worker;

/**
 * Class ProductUpdateWorker
 * @package B2W\SkyHub\Model\Queue\Worker
 */
class ProductUpdateWorker
{
    /**
     * @param $productId
     * @return $this
     * @throws \B2W\SkyHub\Exception\Data\RepositoryNotFound
     */
    public function run($productId)
    {
        $product    = \App::repository(\App::REPOSITORY_PRODUCT)->one($productId);
        /** TODO TEST THIS */
        \App::apiRepository(\App::REPOSITORY_PRODUCT)->save($product);

        return $this;
    }

    /**
     * @param $productId
     * @return mixed
     * @throws \B2W\SkyHub\Exception\Data\RepositoryNotFound
     */
    protected function _getProduct($productId)
    {
        return \App::repository(\App::REPOSITORY_PRODUCT)->one($productId);;
    }
}
