<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Controller\Admin;

use B2W\SkyHub\Model\MapAbstract;
use B2W\SkyHub\View\Admin\Admin;
use B2W\SkyHub\View\Admin\Attribute\EditAbstract;

class Attribute
{
    /** @var MapAbstract */
    protected $_mapInstance     = null;
    /** @var EditAbstract */
    protected $_editInstance    = null;

    public function save()
    {
        if (!isset($_POST['entity_attribute']) || empty($_POST['entity_attribute'])) {
            return $this;
        }

        switch ($_POST['entity_attribute']) {
            case 'catalog/product' :
                $this->_mapInstance     = new \B2W\SkyHub\Model\Catalog\Product\Attribute\Map();
                $this->_editInstance    = new \B2W\SkyHub\View\Admin\Catalog\Product\Attribute\Edit();
                $redirect               = 'admin.php?page=' . Admin::SLUG_CATALOG_PRODUCT_ATTRIBUTE_LIST;
                break;

            case 'sales/order/customer' :
                $this->_mapInstance     = new \B2W\SkyHub\Model\Sales\Order\Customer\Map();
                $this->_editInstance    = new \B2W\SkyHub\View\Admin\Sales\Order\Customer\Edit();
                $redirect               = 'admin.php?page='. Admin::SLUG_SALES_ORDER_CUSTOMER_ATTRIBUTE_LIST;
                break;
        }

        if (!($this->validateNonce() && current_user_can( 'manage_options' ))) {
            $this->_redirect();
            exit;
        }

        $attr       = sanitize_text_field($_POST['attribute-code']);
        $related    = sanitize_text_field($_POST['related-attribute']);

        $this->_mapInstance->setRelated($attr, $related);
        $this->_mapInstance->save();

        $this->_redirect($redirect);

        return $this;
    }

    /**
     * @return bool|int
     */
    private function validateNonce()
    {
        $nonceField     = $this->_nonce('field');
        $nonceAction    = $this->_nonce('action');

        if (!isset($_POST[$nonceField])) {
            return false;
        }

        $field  = wp_unslash($_POST[$nonceField]);

        return wp_verify_nonce($field, $nonceAction);
    }

    private function _nonce($key)
    {
        return $this->_editInstance->nonce($key);
    }


    /**
     * @inheritdoc
     */
    private function _redirect($url = null)
    {
        $url = admin_url($url);
        wp_safe_redirect(urldecode($url));
        exit;
    }
}
