<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Controller\Admin;

use B2W\SkyHub\Model\Setup\Queue as QueueSetup;
use B2W\SkyHub\View\Admin\Admin as AdminView;

class SetupQueue extends AdminControllerAbstract
{
    /**
     * @return mixed
     */
    public function save()
    {
        if (!isset($_POST['page']) || $_POST['page'] != AdminView::SLUG_QUEUE_INTEGRATION_SKYHUB_LIST) {
            return $this;
        }
        
        $queueSetup = new QueueSetup();
        $queueSetup->uninstall();
        
        $jobs = new \B2W\SkyHub\Model\Cron\Jobs();
        $jobs->unsetCronJobs();

        $queueSetup->install();
        $jobs->registerCronJobs();

        $this->_redirect('admin.php?page=' . AdminView::SLUG_QUEUE_INTEGRATION_SKYHUB_LIST);

        return $this;
    }
}
