<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\Skyhub\Controller\Admin\Catalog\Product;


class Attribute
{
    public function save()
    {
        echo 'ok';
        die;
    }


    private function has_valid_nonce() {

        // If the field isn't even in the $_POST, then it's invalid.
        if ( ! isset( $_POST['acme-custom-message'] ) ) { // Input var okay.
            return false;
        }

        $field  = wp_unslash( $_POST['acme-custom-message'] );
        $action = 'acme-settings-save';

        return wp_verify_nonce( $field, $action );

    }
}