<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Controller\Admin\Catalog\Product;


use B2W\SkyHub\Model\Catalog\Product\Attribute\Map;
use B2W\SkyHub\View\Admin\Admin;

/**
 * Class Attribute
 * @package B2W\SkyHub\Controller\Admin\Catalog\Product
 */
class Attribute
{
    const NONCE_ACTION  = 'woocommerce-b2w-skyhub-save-attribute';
    const NONCE_FIELD   = 'woocmmerce-b2w-skyhub-form-key';

    /**
     * @return void
     */
    public function save()
    {
        if (!($this->validateNonce() && current_user_can( 'manage_options' ))) {
            die;
        }

        $map        = new Map();
        $attr       = sanitize_text_field($_POST['attribute-code']);
        $related    = sanitize_text_field($_POST['related-attribute']);

        $map->setRelated($attr, $related);

        $map->save();

        $this->redirect();
    }


    /**
     * @return bool|int
     */
    private function validateNonce()
    {
        if (!isset($_POST[self::NONCE_FIELD])) {
            return false;
        }

        $field  = wp_unslash($_POST[self::NONCE_FIELD]);

        return wp_verify_nonce($field, self::NONCE_ACTION);
    }

    /**
     * @return void
     */
    private function redirect()
    {
        $url = admin_url('admin.php?page=' . Admin::SLUG . '-attribute-list');
        wp_safe_redirect(urldecode($url));
        exit;
    }
}
