<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Contract\Entity\Order\Shipment;

/**
 * Interface ItemEntityInterface
 * @package B2W\SkyHub\Contract\Entity\Order\Shipment
 */
interface ItemEntityInterface
{
    /**
     * @return string
     */
    public function getSku();

    /**
     * @param $sku
     * @return string
     */
    public function setSku($sku);

    /**
     * @return int
     */
    public function getQty();

    /**
     * @param $qty
     * @return int
     */
    public function setQty($qty);
}
