<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Sales\Order\Repository;

use B2W\SkyHub\Contracts\Resource\Repository;
use B2W\SkyHub\Model\Resource\RepositoryAbstract;
use B2W\SkyHub\Model\Sales\Order\Collection;

/**
 * Class Db
 * @package B2W\SkyHub\Model\Sales\Order\Repository
 */
class Api extends RepositoryAbstract implements Repository
{
    /**
     * @param array $filters
     * @return \B2W\SkyHub\Contracts\Resource\Collection|Collection
     */
    public function all($filters = array())
    {
        return new Collection();
    }

    /**
     * @param $id
     * @return mixed|null
     * @throws \B2W\SkyHub\Exception\Data\TransformerNotFound
     * @throws \B2W\SkyHub\Exception\Helper\HelperNotFound
     */
    public function one($id)
    {
        $requestHandler = \App::api()->order();
        $response       = $requestHandler->order($id);

        if ($response->exception()) {
            throw new \Exception($response->message());
        }

        $transformer    = \App::transformer('sales/order/api_to_entity');
        $transformer->setResponse($response);

        $order  = $transformer->convert($response);

        return $order;
    }
}
