<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Sales\Order\Repository;

use B2W\SkyHub\Contracts\Resource\Repository;
use B2W\SkyHub\Model\Resource\RepositoryAbstract;
use B2W\SkyHub\Model\Sales\Order\Collection;
use B2W\SkyHub\Model\Sales\Order\Entity;

class Db extends RepositoryAbstract implements Repository
{
    public function all($filters = array())
    {
        $defaultFilter = array(
            'post_type' => Entity::POST_TYPE
        );

        $posts = get_posts($defaultFilter);

        $collection = new Collection();

        foreach ($posts as $post) {
            $product = $this->one($post);
            $collection->addItem($product);
        }

        return $collection;
    }

    public function one($id)
    {
        if ($id instanceof \WP_Post) {
            $post = $id;
        } else {
            $post = get_post($id);
        }

        $order = $this->emptyOne();

        if ($post->post_type != Entity::POST_TYPE) {
            return $order;
        }

        \B2W\SkyHub\Model\Transformer\Post\Sales\Order::convert($post, $order);

        return $order;
    }

    public function emptyOne()
    {
        return new Entity();
    }

    public function emptyCollection()
    {
        return new Collection();
    }
}
