<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Sales\Order\Repository;

use B2W\SkyHub\Contracts\Resource\Repository;
use B2W\SkyHub\Model\Resource\RepositoryAbstract;
use B2W\SkyHub\Model\Sales\Order\Collection;
use B2W\SkyHub\Model\Sales\Order\Entity;
use B2W\SkyHub\Model\Transformer\Sales\Order\Post;

/**
 * Class Db
 * @package B2W\SkyHub\Model\Sales\Order\Repository
 */
class Db extends RepositoryAbstract implements Repository
{
    /**
     * @param array $filters
     * @return \B2W\SkyHub\Contracts\Resource\Collection|Collection
     */
    public function all($filters = array())
    {
        $defaultFilter = array(
            'post_type' => Entity::POST_TYPE
        );

        foreach ($filters as $k => $v) {
            $defaultFilter[$k] = $v;
        }

        $posts = get_posts($defaultFilter);

        $collection = new Collection();

        foreach ($posts as $post) {
            $order = $this->one($post);
            $collection->addItem($order);
        }

        return $collection;
    }

    /**
     * @param $id
     * @return Entity|mixed
     */
    public function one($id)
    {
        if ($id instanceof \WP_Post) {
            $post = $id;
        } else {
            $post = get_post($id);
        }

        $order = new Entity();

        if ($post->post_type != Entity::POST_TYPE) {
            return $order;
        }

        \B2W\SkyHub\Model\Transformer\Post\Sales\Order::convert($post, $order);

        return $order;
    }

    public function save(Entity $order)
    {
        $data = Post::convert($order);
        wp_insert_post(Post::convert($order));
    }
}
