<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Integrator;


/**
 * Class IntegratorAbstract
 * @package B2W\SkyHub\Model\Integrator
 */
abstract class IntegratorAbstract
{
    /**
     * @var string
     */
    protected $eventPrefix = 'woocommerce-b2w-skyub_integrator';
    protected $eventType   = null;
    protected $eventMethod = null;
    protected $eventSuffix = null;
    protected $eventParams = array();


    /**
     * IntegratorAbstract constructor.
     */
    public function __construct()
    {
        $this->init();
    }


    /**
     * @return $this
     */
    protected function init()
    {
        return $this;
    }


    /**
     * @return string
     */
    protected function getEventName()
    {
        return vsprintf('%s_%s_%s_$s', array(
            $this->eventPrefix,
            $this->eventType,
            $this->eventMethod,
            $this->eventSuffix,
        ));
    }


    /**
     * @return $this
     */
    protected function resetEvent()
    {
        $this->eventType   = null;
        $this->eventMethod = null;

        return $this;
    }


    /**
     * @return $this
     */
    protected function beforeIntegration()
    {
        $this->resetEvent();

        $this->eventSuffix = 'before';
        \App::dispatchEvent($this->getEventName(), (array) $this->eventParams);
        return $this;
    }


    /**
     * @return $this
     */
    protected function afterIntegration()
    {
        $this->eventSuffix = 'after';
        \App::dispatchEvent($this->getEventName(), (array) $this->eventParams);
        return $this;
    }
}
