<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Transformer\Catalog\Product;

use B2W\SkyHub\Model\Map\Catalog\Product\Map;
use B2W\SkyHub\Model\Transformer\EntityToApiAbstract;

/**
 * Class EntityToApi
 * @package B2W\SkyHub\Model\Transformer\Catalog\Product
 */
class EntityToApi extends EntityToApiAbstract
{
    /**
     * @return Map|mixed
     */
    protected function _getAttributeMapInstance()
    {
        return new Map();
    }

    /**
     * @return \SkyHub\Api\EntityInterface\Catalog\Product
     */
    protected function _getInterfaceInstance()
    {
        return \App::api()->product()->entityInterface();
    }
}
