<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\Skyhub\Model\Data\Converter\Post;

/**
 * Class EntityAbstract
 * @package B2W\Skyhub\Model\Data\Converter\Post
 */
abstract class EntityAbstract
{
    /**
     * @var array
     */
    protected $_map = array();


    /**
     * @param $post
     * @param $entity
     * @return EntityAbstract|bool
     */
    public static function convert($post, $entity)
    {
        static $instance = false;
        if ($instance === false) {
            $instance = new static();
        }

        $instance->_init();
        $instance->_convert($post, $entity);

        return $instance;
    }

    /**
     * EntityAbstract constructor.
     */
    private function __construct()
    {
        return $this;
    }


    /**
     * @return $this
     */
    private function __clone()
    {
        return $this;
    }


    /**
     * @return mixed
     */
    abstract protected function _init();

    /**
     * @param $postAttribute
     * @param $entityAttribute
     * @return $this
     */
    protected function _addMap($postAttribute, $entityAttribute)
    {
        $this->_map[$postAttribute] = $entityAttribute;
        return $this;
    }

    /**
     * @param \WP_Post $post
     * @param $entity
     * @return $this
     */
    protected function _convert($post, $entity)
    {
        $meta = get_post_meta($post->ID);

        foreach ($this->_map as $postAttribute => $entityAttribute) {
            $method = 'set' . ucfirst($entityAttribute);
            if (!method_exists($entity, $method)) {
                continue;
            }

            $value = property_exists($post, $postAttribute)
                ? $post->$postAttribute
                : (key_exists($postAttribute, $meta) ? current($meta[$postAttribute]) : null);

            if (!$value) {
                continue;
            }

            $entity->$method($value);
        }

        return $this;
    }
}
