<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Sales\Order\Shipment\Item;

/**
 * Class Entity
 * @package B2W\SkyHub\Model\Sales\Order\Shipment\Item
 */
class Entity implements \B2W\SkyHub\Contracts\Sales\Order\Shipment\Item\Entity
{
    /** @var string */
    protected $_sku = null;
    /** @var int */
    protected $_qty = null;

    /**
     * @return string
     */
    public function getSku()
    {
        return $this->_sku;
    }

    /**
     * @param string $sku
     */
    public function setSku($sku)
    {
        $this->_sku = $sku;
    }

    /**
     * @return int
     */
    public function getQty()
    {
        return $this->_qty;
    }

    /**
     * @param int $qty
     */
    public function setQty($qty)
    {
        $this->_qty = $qty;
    }
}
