<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\Skyhub\Model\Order;

use B2W\Skyhub\Data\EntityAbstract;

class Entity implements \B2W\Skyhub\Contracts\Order\Entity
{
    const POST_TYPE = 'shop_order';

    public function getId()
    {
        // TODO: Implement getId() method.
    }

    public function setId()
    {
        // TODO: Implement setId() method.
    }

    public function items()
    {
        // TODO: Implement items() method.
    }

    public function shipment()
    {
        // TODO: Implement shipment() method.
    }

    public function save()
    {
        // TODO: Implement save() method.
    }
}
