<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\Skyhub\Model\Order;

use B2W\Skyhub\Data\EntityAbstract;

class Entity extends EntityAbstract implements \B2W\Skyhub\Contracts\Order\Entity
{
    const POST_TYPE = 'shop_order';

    protected $_id = null;

    public function load($id)
    {
        if ($id instanceof \WP_Post) {
            $post = $id;
        } else {
            $post = get_post($id);
        }

        $this->_id = $post->ID;

        return $this;
    }

    public function items()
    {
        // TODO: Implement items() method.
    }

    public function shipment()
    {
        // TODO: Implement shipment() method.
    }

    public function setData($key, $value = null)
    {
        // TODO: Implement setData() method.
    }

    public function save()
    {
        // TODO: Implement save() method.
    }
}
