<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Transformer\Sales\Order\Item;

use B2W\SkyHub\Model\Sales\Order\Item\Collection;
use B2W\SkyHub\Model\Sales\Order\Item\Entity;
use B2W\SkyHub\Model\Transformer\ApiToEntityAbstract;

/**
 * Class PostToEntity
 * @package B2W\SkyHub\Model\Transformer\Sales\Order\Item
 */
class ApiToEntity extends ApiToEntityAbstract
{
    /**
     * @return mixed|null
     */
    protected function _getEntityInstance()
    {
        return null;
    }

    /**
     * @return mixed|null
     */
    protected function _getMapInstance()
    {
        return null;
    }

    /**
     * @return Collection|mixed|null
     * @throws \B2W\SkyHub\Exception\Data\RepositoryNotFound
     */
    public function convert()
    {
        $collection = new Collection();

        foreach ($this->_prepareData() as $data) {
            $item = new Entity();
            $item->setId($data['id']);
            $item->setName($data['name']);
            $item->setProduct(\App::repository(\App::REPOSITORY_CATALOG_PRODUCT)->sku($data['id']));
            $item->setOriginalPrice($data['original_price']);
            $item->setSpecialPrice($data['special_price']);
            $item->setShippingCost($data['shipping_cost']);
            $item->setQty($data['qty']);

            $collection->addItem($item);
        }

        return $collection;
    }
}
