<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Transformer\Sales\Order\Item;

use B2W\SkyHub\Model\Map\Attribute;
use B2W\SkyHub\Model\Map\Sales\Order\Item\Map;
use B2W\SkyHub\Model\Transformer\EntityToDbAbstract;

/**
 * Class PostToEntity
 * @package B2W\SkyHub\Model\Transformer\Sales\Order\Item
 */
/** @method \B2W\SkyHub\Model\Sales\Order\Entity getEntity() */
class EntityToDb extends EntityToDbAbstract
{
    protected function _getMapInstance()
    {
        return new Map();
    }

    protected function _getTableName()
    {
        return 'woocommerce_order_items';
    }

    protected function _getEntityValue(Attribute $attribute)
    {
        $method = $this->_helper()->getGetterMethodName($this->getEntity(), $attribute->getSkyhub());

        if (!$method) {
            return '';
        }

        return $this->getEntity()->$method();
    }
}
