<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Transformer\Sales\Order\Item;

use B2W\SkyHub\Model\Sales\Order\Item\Entity;
use B2W\SkyHub\Model\TransformerAbstract;

/**
 * Class Post
 * @package B2W\SkyHub\Model\Transformer\Sales\Order\Address
 */
class Post extends TransformerAbstract
{
    static public function convert($items)
    {
        /** @var  $instance */
        $instance = static::_instantiate();
        return $instance->_convert($items);
    }

    protected function _convert($items)
    {
        $return = array();

        /** @var Entity $item */
        foreach ($items as $item) {
            $product = \App::repository(\App::REPOSITORY_CATALOG_PRODUCT)->sku($item->getId());

            /*
            if ($product === false) {

            }
            */

        }

        return $return;
    }
}
