<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Transformer\Sales\Order;

use B2W\SkyHub\Model\Sales\Order\Entity;
use B2W\SkyHub\Model\Map\Sales\Order\Map;
use B2W\SkyHub\Model\Transformer\PostToEntityAbstract;

/**
 * Class PostToEntity
 * @package B2W\SkyHub\Model\Transformer\Sales\Order
 */
class PostToEntity extends PostToEntityAbstract
{
    /**
     * @return array|mixed
     */
    protected function _getAttributeMap()
    {
        $map = new Map();
        return $map->map();
    }

    /**
     * @return Entity|null
     */
    public function _getEntityInstance()
    {
        return new Entity();
    }
}
