<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Transformer\Sales\Order;

use B2W\SkyHub\Helper\App;
use B2W\SkyHub\Model\Sales\Order\Entity;
use B2W\SkyHub\Model\Sales\Order\Map;
use B2W\SkyHub\Model\TransformerAbstract;

class Post extends TransformerAbstract
{
    static public function convert(Entity $order)
    {
        $instance = static::_instantiate();
        return $instance->_convert($order);
    }

    protected function _convert(Entity $order)
    {
        $map    = new Map();
        /** @var App $helper */
        $helper = \App::helper('app');
        $data   = array();

        foreach ($map->map() as $attribute) {

            $method = $helper->getGetterMethodName($order, $attribute['skyhub']);

            if (!$method) {
                continue;
            }

            if (strpos($attribute['local'], '_') === 0) {
                $data['meta_input'][$attribute['local']] = $order->$method();
                continue;
            }

            $data[$attribute['local']] = $order->$method();
        }

        return $data;
    }
}
