<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Transformer\Sales\Order;


use B2W\SkyHub\Model\Sales\Order\Status\Entity;
use B2W\SkyHub\Model\TransformerAbstract;

/**
 * Class Status
 * @package B2W\SkyHub\Model\Transformer\Sales\Order
 */
class Status extends TransformerAbstract
{
    /** @var Entity */
    protected $_entity      = null;
    /**
     * @var null
     */
    protected $_wcStatus    = null;

    /**
     * @param Entity $status
     * @param $wcStatus
     * @return Status
     */
    final public static function convert(Entity $status, $wcStatus)
    {
        /** @var self $instance */
        $instance = static::_instantiate();

        $instance->_entity      = $status;
        $instance->_wcStatus    = $wcStatus;

        $instance->_convert();
        $instance->_reset();

        return $instance;
    }

    /**
     * @return $this
     */
    protected function _reset()
    {
        $this->_entity      = null;
        $this->_wcStatus    = null;

        return $this;
    }

    /**
     * @return $this
     */
    protected function _convert()
    {
        $this->_entity->setType('teste');
        $this->_entity->setLabel('Teste');
        $this->_entity->setCode($this->_wcStatus);

        return $this;
    }
}
