<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\Skyhub\Model\Catalog\Product\Converter\Post;

use B2W\Skyhub\Model\Data\Converter\Post\EntityAbstract;

/**
 * Class Entity
 * @package B2W\Skyhub\Contracts\Catalog\Product\Converter\Post
 */
class Entity extends EntityAbstract
{
    /**
     * @return $this|mixed
     */
    protected function _init()
    {
        $map = array(
            'ID'            => 'id',
            'post_title'    => 'name',
            'post_status'   => 'status',
            'post_content'  => 'description',
            '_sku'          => 'sku',
            '_stock'        => 'qty',
            '_price'        => 'price',
            //'_promoPrice'   => 'promotionalPrice',//TODO: special price
            '_weight'       => 'weight',
            '_height'       => 'height',
            '_length'       => 'length',
            '_width'        => 'width',
        );

        //TODO MAP CUSTOM ATTRIBUTES IN ADMIN
        //bran
        //ean
        //nbm

        foreach ($map as $post => $entity) {
            $this->_addMap($post, $entity);
        }

        return $this;
    }
}
