<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Sales\Order\Customer\Repository;

use B2W\SkyHub\Contracts\Resource\Sales\Order\Repository;
use B2W\SkyHub\Model\Resource\RepositoryAbstract;

/**
 * Class Db
 * @package B2W\SkyHub\Model\Customer\Repository
 */
class Db extends RepositoryAbstract implements Repository
{
    /**
     * @param \B2W\SkyHub\Contracts\Sales\Order\Entity $order
     * @return \B2W\SkyHub\Contracts\Sales\Order\Customer\Entity|mixed
     * @throws \B2W\SkyHub\Exception\Helper\HelperNotFound
     */
    public function get(\B2W\SkyHub\Contracts\Sales\Order\Entity $order)
    {
        $customerId = get_post_meta($order->getId(), '_customer_user', true);
        $customer   = new \B2W\SkyHub\Model\Sales\Order\Customer\Entity();
        $customer->setId($customerId);
        \B2W\SkyHub\Model\Transformer\User\Customer::convert($customer);
        \B2W\SkyHub\Model\Transformer\Sales\Order\Customer::convert($order, $customer);

        return $customer;
    }
}
