<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Sales\Order\Customer\Repository;

use B2W\SkyHub\Contracts\Resource\Sales\Order\Customer\Repository;
use B2W\SkyHub\Model\Resource\RepositoryAbstract;

/**
 * Class Db
 * @package B2W\SkyHub\Model\Customer\Repository
 */
class Db extends RepositoryAbstract implements Repository
{
    /**
     * @param \B2W\SkyHub\Contracts\Sales\Order\Entity $order
     * @return \B2W\SkyHub\Contracts\Sales\Order\Customer\Entity|mixed
     */
    public function get(\B2W\SkyHub\Contracts\Sales\Order\Entity $order)
    {
        $post       = get_post($order->getId());
        $customer   = new \B2W\SkyHub\Model\Sales\Order\Customer\Entity();
        \B2W\SkyHub\Model\Transformer\Sales\Order\Customer\PostToEntity::convert($post, $customer);

        return $customer;
    }

    public function cpf($cpf)
    {
        // TODO: Implement cpf() method.
    }

    public function cnpj($cnpj)
    {
        // TODO: Implement cnpj() method.
    }
}
