<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Resource\Catalog\Product\Repository;

use B2W\SkyHub\Contracts\Resource\Catalog\Product\Repository;
use B2W\SkyHub\Model\Catalog\Product\Entity;
use B2W\SkyHub\Model\Catalog\Product\Collection;
use B2W\SkyHub\Model\Resource\RepositoryAbstract;
use B2W\SkyHub\Model\Resource\Select;

/**
 * Class Db
 * @package B2W\SkyHub\Model\Order\Repository
 */
class Db extends RepositoryAbstract implements Repository
{
    /**
     * @param array $filter
     * @return \B2W\SkyHub\Contracts\Resource\Collection|Collection
     * @throws \Exception
     */
    public function find($filter = array())
    {
        $defaultFilter = array(
            'post_status'   => array('publish'),
            'post_type'     => Entity::POST_TYPE
        );

        $posts = get_posts($defaultFilter);

        $collection = new Collection();

        foreach ($posts as $post) {
            $product = $this->one($post);
            $collection->addItem($product);
        }

        return $collection;
    }

    /**
     * @param $post
     * @return Entity
     * @throws \Exception
     */
    public function one($post)
    {
        if (!$post instanceof \WP_Post) {
            $post = get_post($post);
        }

        $product = new Entity();

        if ($post->post_type != Entity::POST_TYPE) {
            return false;
        }

        /** @var \B2W\SkyHub\Model\Transformer\Catalog\Product\PostToEntity $transformer */
        $transformer = \App::transformer('catalog/product/post_to_entity');
        $transformer->setPost($post);
        $transformer->setEntity($product);

        return $transformer->convert();
    }

    /**
     * @param $sku
     * @return \B2W\SkyHub\Contracts\Catalog\Product\Entity|Entity|bool
     * @throws \Exception
     */
    public function sku($sku)
    {
        global $wpdb;

        $sku = sanitize_text_field($sku);

        $select = new Select();
        $select->column('post_id');
        $select->from('postmeta');
        $select->where("meta_key = '_sku'");
        $select->where("meta_value= '$sku'");

        foreach ($wpdb->get_results($select) as $row) {
            return $this->one($row->post_id);
        }

        return false;
    }
}
