<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\Skyhub\Model\Data\Repository;

use B2W\Skyhub\Contracts\Data\RepositoryFactory;

abstract class FactoryAbstract
{
    protected static function instantiate($baseClassName, $repositoryType = null)
    {
        $repositoryType = $repositoryType == null ? RepositoryFactory::DEFAULT_REPOSITORY : $repositoryType;
        $className      = $baseClassName . ucfirst($repositoryType);

        if (!class_exists($className)) {
            throw new \Exception(
                'Class ' . $className . ' não encontrada. Verifique a existencia do repositório ' . $repositoryType
            );
        }

        return new $className;
    }
}
