<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Transformer\Api\Sales;

use B2W\SkyHub\Model\TransformerAbstract;

/**
 * Class Collection
 * @package B2W\SkyHub\Model\Transformer\Api\Sales\Order\Item
 */
abstract class CollectionAbstract extends TransformerAbstract
{
    /**
     * @return mixed
     */
    abstract protected function _getCollection();

    /**
     * @return mixed
     */
    abstract protected function _getTransformerName();

    /**
     * @param array $value
     * @return \B2W\SkyHub\Model\Sales\Order\Item\Collection
     */
    static public function convert(array $value)
    {
        /** @var self $instance */
        $instance = static::_instantiate();
        return $instance->_convert($value);
    }

    /**
     * @param $value
     * @return \B2W\SkyHub\Model\Sales\Order\Item\Collection
     */
    protected function _convert($value)
    {
        /** @var \B2W\SkyHub\Model\Sales\Order\Item\Collection $collection */
        $collection     = $this->_getCollection();
        $transformer    = $this->_getTransformerName();

        foreach ($value as $item) {
            $item = $transformer::convert($item);
            $collection->addItem($item);
        }

        return $collection;
    }
}
