<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Contracts\Resource\Sales\Order\Address;

use B2W\SkyHub\Contracts\Resource\Collection;
use B2W\SkyHub\Contracts\Sales\Order\Entity;

/**
 * Interface Repository
 * @package B2W\SkyHub\Contracts\Resource\Sales\Order
 */
interface Repository
{
    /**
     *
     */
    const TYPE_BILLING  = 'billing';
    /**
     *
     */
    const TYPE_SHIPPING = 'shipping';

    /**
     * @param Entity $order
     * @param string $type
     * @return \B2W\SkyHub\Contracts\Sales\Order\Address\Entity
     */
    public function load(Entity $order, $type = 'billing');

    /**
     * @param Entity $order
     * @return \B2W\SkyHub\Contracts\Sales\Order\Address\Entity
     */
    public function billing(Entity $order);

    /**
     * @param Entity $order
     * @return \B2W\SkyHub\Contracts\Sales\Order\Address\Entity
     */
    public function shipping(Entity $order);
}
