<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\View\Admin\Catalog\Product\Attribute;

use B2W\SkyHub\Model\Catalog\Product\Attribute\Entity;
use B2W\SkyHub\Model\Catalog\Product\Attribute\Map;
use B2W\SkyHub\View\Template;

/**
 * Class Edit
 * @package B2W\SkyHub\View\Admin\Catalog\Product\Attribute
 */
class Edit extends Template
{
    /**
     * @var string
     */
    protected $_template    = 'catalog/product/attribute/edit.php';
    /**
     * @var null
     */
    protected $_attribute   = null;

    /**
     * @param null $key
     * @return null|string
     */
    public function getAttribute($key = null)
    {
        if (is_null($this->_attribute)) {
            $this->_loadAttributes();
        }

        if (is_null($key)) {
            return $this->_attribute;
        }

        return isset($this->_attribute[$key]) ? $this->_attribute[$key] : '';
    }

    /**
     * @return bool|string
     */
    public function getMapped()
    {
        $attr   = $this->getAttribute('code');
        $map    = new Map();
        return $map->attribute($attr);
    }

    /**
     * @return array
     * @throws \B2W\SkyHub\Exception\Data\RepositoryNotFound
     */
    public function getLocalAttributeList()
    {
        $base = array(
            '_sku',
            '_regular_price',
            '_sale_price',
            '_weight',
            '_length',
            '_width',
            '_height',
            '_stock',
            '_price',
            'post_title',
            'post_content',
            'post_status'
        );

        /** @var Entity $attribute */
        foreach (\App::repository('catalog/product/attribute')->all() as $attribute) {
            $base[] = $attribute->getCode();
        }

        return $base;
    }

    /**
     * @return $this
     */
    private function _loadAttributes()
    {
        $code = isset($_GET['attribute']) ? $_GET['attribute'] : null;
        $list = \App::getConfig('catalog/product/attribute/skyhub');

        foreach ($list as $attribute) {
            if ($attribute['code'] == $code) {
                $this->_attribute = $attribute;
                break;
            }
        }

        return $this;
    }
}
