<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\Skyhub\View\Admin\Catalog\Product\Attribute;

use B2W\Skyhub\Model\Catalog\Product\Attribute\Map;
use B2W\Skyhub\View\Template;

class Edit extends Template
{
    protected $_template    = 'catalog/product/attribute/edit.php';
    protected $_attribute   = null;

    public function getAttribute($key = null)
    {
        if (is_null($this->_attribute)) {
            $this->_loadAttributes();
        }

        if (is_null($key)) {
            return $this->_attribute;
        }

        return isset($this->_attribute[$key]) ? $this->_attribute[$key] : '';
    }

    public function getMapped()
    {
        $attr   = $this->getAttribute('code');
        $map    = new Map();
        return $map->attribute($attr);
    }

    public function getLocalAttributeList()
    {
        return array(
            '_sku'
        );
    }

    private function _loadAttributes()
    {
        $code = isset($_GET['attribute']) ? $_GET['attribute'] : null;
        $list = \App::getConfig('catalog/product/attribute/skyhub');

        foreach ($list as $attribute) {
            if ($attribute['code'] == $code) {
                $this->_attribute = $attribute;
                break;
            }
        }

        return $this;
    }
}
