<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\Skyhub\Model\Catalog\Attribute\Repository;

use B2W\Skyhub\Model\Catalog\Attribute\Entity;
use B2W\Skyhub\Model\Catalog\Attribute\Collection;

/**
 * Class Db
 * @package B2W\Skyhub\Model\Order\Repository
 */
class Db implements \B2W\Skyhub\Contracts\Data\Repository
{
    /**
     * @return \B2W\Skyhub\Contracts\Data\Collection|Collection
     */
    public static function all()
    {
        global $wpdb;

        $query      = self::_getQuery();
        $results    = $wpdb->get_results($query);

        $collection = new Collection();

        $attributes = array();

        foreach ($results as $result) {
            $attribute = self::one($result->attribute_id);
            $collection->addItem($attribute);
        }

        return $collection;
    }

    /**
     * @param $id
     * @return Entity
     */
    public static function one($id)
    {
        global $wpdb;

        $query = $wpdb->prepare(self::_getQuery() . " WHERE main_table.attribute_id = %s", $id);

        echo $query;die;



        if ($id instanceof \WP_Post) {
            $post = $id;
        } else {
            $post = get_post($id);
        }

        $order = new Entity();
        $order->setId($post->ID);

        return $order;
    }

    public static function emptyOne()
    {
        return new Entity();
    }

    protected static function _getQuery()
    {
        global $wpdb;

        return <<<QUERY
SELECT attribute_id, attribute_name, attribute_label, terms.term_id, terms.name
FROM {$wpdb->prefix}woocommerce_attribute_taxonomies AS main_table
JOIN {$wpdb->prefix}term_taxonomy AS term_taxonomy
  ON term_taxonomy.taxonomy = CONCAT('pa_', main_table.attribute_name)
JOIN {$wpdb->prefix}terms AS terms
  ON terms.term_id = term_taxonomy.term_id
QUERY;
    }
}
