<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\Skyhub\Controller\Admin\Catalog;


use B2W\Skyhub\Model\Catalog\Product\Entity;

class Product
{
    public function onSave()
    {
        if ($_POST['post_type'] !== Entity::POST_TYPE) {
            return $this;
        }

        /** TODO integrate product */
        try {
            //integrate
        } catch (\Exception $e) {
            //add to queue
        }

        return $this;
    }
}
