<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Contracts\Customer;


/**
 * Interface Entity
 * @package B2W\SkyHub\Contracts\Customer
 */
interface Entity
{
    /**
     * @return int
     */
    public function getId();

    /**
     * @param $id
     * @return int
     */
    public function setId($id);

    /**
     * @return string
     */
    public function getName();

    /**
     * @param $name
     * @return string
     */
    public function setName($name);

    /**
     * @return string
     */
    public function getEmail();

    /**
     * @param $email
     * @return string
     */
    public function setEmail($email);

    /**
     * @return \DateTime
     */
    public function getDateOfBirth();

    /**
     * @param $date_of_birth
     * @return \DateTime
     */
    public function setDateOfBirth($date_of_birth);

    /**
     * @return string
     */
    public function getGender();

    /**
     * @param $gender
     * @return string
     */
    public function setGender($gender);

    /**
     * @return string
     */
    public function getVatNumber();

    /**
     * @param $vat_number
     * @return string
     */
    public function setVatNumber($vat_number);

    /**
     * @return array
     */
    public function getPhones();

    /**
     * @param $phones
     * @return array
     */
    public function setPhones($phones);

    /**
     * @return string
     */
    public function getStateRegistration();

    /**
     * @param $state_registration
     * @return string
     */
    public function setStateRegistration($state_registration);
}
