<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\Skyhub\Contracts\Data;

interface RepositoryFactory
{
    /**
     * Defines wich repository to use by default
     */
    const DEFAULT_REPOSITORY = 'db';

    /**
     * @param null $repositoryType
     * @return \B2W\Skyhub\Contracts\
     */
    public function create($repositoryType = null);
}
