<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\Skyhub\Contracts\Data;


/**
 * Interface Repository
 * @package B2W\Skyhub\Contracts\Data
 */
interface Repository
{
    /**
     * @return \B2W\Skyhub\Contracts\Data\Collection
     */
    public static function all();

    /**
     * @param $id
     * @return mixed
     */
    public static function one($id);


    /**
     * @return mixed
     */
    public static function emptyOne();
}
