<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Controller;

use B2W\SkyHub\Contract\Entity\OrderEntityInterface;
use B2W\SkyHub\Model\Map\Order\StatusMap;

class Order
{
    public function update($orderId, $statusFrom, $statusTo, $wcOrder)
    {
        $skyhubAction = null;

        $map = new StatusMap();

        foreach ($map->map() as $attribute) {
            if ($attribute->getWordpress() == 'wc-' . $statusTo) {
                $skyhubAction = $attribute->getSkyhub();
                break;
            }
        }

        $methodName = '_' . $skyhubAction;
        if (method_exists($this, $methodName)) {
            $order = \App::repository(\App::REPOSITORY_ORDER)->one($orderId);
            $this->$methodName($order);
        }

        return $this;
        /** TODO WHEN UPDATE ORDER IN ADMIN */
        /** CHECK IF NEED TO UPDATE SKYHUB BASED ON STATUS MAP */
    }

    protected function _shipped(OrderEntityInterface $order)
    {
        /** TODO add to queue instead of call API */
        try {
            \App::apiRepository(\App::REPOSITORY_ORDER)->shipp($order);
        } catch (\Exception $e) {
            \App::logException($e);
            return false;
        }

        return true;
    }
}
