<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Controller;


use B2W\SkyHub\Model\Entity\ProductEntity;
use B2W\SkyHub\Model\Queue\Message\ProductUpdateMessage;

/**
 * Class Product
 * @package B2W\SkyHub\Controller
 */
class Product
{
    /**
     * @return $this
     * @throws \B2W\SkyHub\Exception\Data\RepositoryNotFound
     * @throws \B2W\SkyHub\Exception\Exception
     */
    public function onSave()
    {
        $message = new ProductUpdateMessage($_POST['post_ID']);
        \App::repository(\App::REPOSITORY_QUEUE)->add($message);

        return $this;
    }
}
