<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Controller;


use B2W\SkyHub\Model\Entity\ProductEntity;

/**
 * Class Product
 * @package B2W\SkyHub\Controller
 */
class Product
{
    /**
     * @return $this
     */
    public function onSave()
    {
        if ($_POST['post_type'] !== ProductEntity::POST_TYPE) {
            return $this;
        }

        try {
            /** TODO ADD TO QUEUE INSTEAD OF INTEGRATE IN REAL TIME */
            /** @var ProductEntity $product */
            $product    = \App::repository(\App::REPOSITORY_PRODUCT)->one($_POST['post_ID']);
            $integrator = new \B2W\SkyHub\Model\Integrator\Catalog\Product();
            $integrator->createOrUpdate($product);
            \App::log('Product '.$product->getSku().' saved');
        } catch (\Exception $e) {
            \App::logException($e);
        }

        return $this;
    }
}
