<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2019 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Tiago Tescaro <tiago.tescaro@b2wdigital.com>
 */
namespace B2W\SkyHub\View\Admin\Settings\Api;

use B2W\SkyHub\View\Admin\Form\FormAbstract;
use B2W\SkyHub\Model\Entity\SettingsApiEntity;

class View extends FormAbstract
{
    /**
     * @return $this|mixed
     * @throws \B2W\SkyHub\Exception\Helper\HelperNotFound
     */
    protected function _prepareForm()
    {
        $settingsApi = new SettingsApiEntity();
        $settingsApi->map();
        $fieldset = $this->_addFieldset('api', 'API');
        $fieldset->addField(
            'text',
            'email',
            array(
                'label'   => 'Email',
                'value'   => $settingsApi->getEmail()
            )
        );
        $fieldset->addField(
            'text',
            'apiKey',
            array(
                'label'   => 'API Key',
                'value'   => $settingsApi->getApiKey()
            )
        );
        return $this;
    }
}