<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\Skyhub\View\Admin;


use B2W\Skyhub\Controller\Admin\Catalog\Product;
use B2W\Skyhub\View\Admin\Catalog\Product\Attribute\Edit;
use B2W\Skyhub\View\Admin\Catalog\Product\Attribute\Page;

class Admin
{
    const SLUG          = 'woocommerce-b2w-skyhub';
    const PERMISSION    = 'manage_options';
    const DOMAIN        = 'b2w_skyhub';

    public function init()
    {
        add_action('admin_menu', array($this, 'menu'));
        add_action('admin_post', array(new \B2W\Skyhub\Controller\Admin\Catalog\Product\Attribute(), 'save'));

        //product save event
        add_action('save_post', array(new Product(), 'onSave'));

        return $this;
    }

    public function menu()
    {
        $attributesPage = new Page();

        add_menu_page(
            'Skyhub',
            'Skyhub',
            self::PERMISSION,
            self::SLUG,
            array($attributesPage, 'render'),
            'dashicons-tickets'
        );

        add_submenu_page(
            self::SLUG,
            __('Product Attributes', self::DOMAIN),
            __('Product Attributes', self::DOMAIN),
            self::PERMISSION,
            self::SLUG . '-attribute-list',
            array($attributesPage, 'render')
        );

        add_submenu_page(
            null,
            __('Product Attribute Edit', self::DOMAIN),
            __('Product Attribute Edit', self::DOMAIN),
            self::PERMISSION,
            self::SLUG . '-attribute-edit',
            array(new Edit(), 'render')
        );

        return $this;
    }
}
