<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\View\Admin;

/**
 * Class GridAbstract
 * @package B2W\SkyHub\View
 */
abstract class GridAbstract extends \WP_List_Table
{
    const COLUMN_SKYHUB_CODE    = 'skyhub_code';
    const COLUMN_LOCAL_CODE     = 'local_code';
    const COLUMN_SKYHUB_NAME    = 'skyhub_name';
    const COLUMN_DESCRIPTION    = 'description';

    protected $_options         = null;

    /**
     * Attribute constructor.
     * @param array $args
     */
    public function __construct($args = array())
    {
        parent::__construct(
            array(
                'singular'  => 'product_attribute',
                'plural'    => 'product_attributes',
                'ajax'      => false
            )
        );

        $this->_loadItems();
    }

    /**
     * @param string $which
     */
    protected function extra_tablenav($which)
    {
        switch ($which) {
            case 'top' :
                $this->_addTopContent();
                break;
            case 'bottom' :
                $this->_addBottomContent();
                break;
        }

        parent::extra_tablenav($which);
    }

    /**
     * @return array
     */
    public function get_columns()
    {
        return array(
            self::COLUMN_SKYHUB_NAME    => __('Attribute'),
            self::COLUMN_SKYHUB_CODE    => __('SkyHub Code'),
            self::COLUMN_LOCAL_CODE     => __('Woocommerce Code'),
//            self::COLUMN_DESCRIPTION    => __('Attribute Description'),
        );
    }

    /**
     * @inheritdoc
     */
    public function prepare_items()
    {
        $this->_column_headers = array($this->get_columns(), array(), $this->get_sortable_columns());

        $screen     = get_current_screen();
        $columns    = $this->get_columns();

        $this->set_pagination_args(
            array(
                'total_items'   => count($this->items),
                'total_pages'   => 1,
                'per_page'      => count($this->items),
            )
        );

        $_wp_column_headers[$screen->id] = $columns;
    }

    /**
     * @inheritdoc
     */
    public function display_rows()
    {
        $records = $this->items;

        if (!empty($records)) {
            foreach ($records as $record){
                $this->_renderRow($record);
            }
        }
    }

    /**
     * @param $rowData
     */
    protected function _renderRow($rowData)
    {
        echo '<tr id="record_">';

        foreach ($this->get_columns() as $colCode => $colTitle) {
            echo '<td>';
            if (isset($rowData[$colCode])) {
                echo $rowData[$colCode];
            }
            echo '</td>';
        }

        echo '</tr>';
    }

    /**
     * @return mixed
     */
    abstract protected function _loadItems();
}
