<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Transformer\Catalog\Product\VariationAttributes;

use B2W\SkyHub\Model\Catalog\Product\Attribute\Collection;
use B2W\SkyHub\Model\Catalog\Product\Attribute\Entity;

/**
 * Class EntityToApi
 * @package B2W\SkyHub\Model\Transformer\Catalog\Product\VariationAttribute
 */
class EntityToApi
{
    public function convert(Collection $collection, $parentTranformer)
    {
        /** @var \SkyHub\Api\EntityInterface\Catalog\Product $productInterface */
        $productInterface   = $parentTranformer->getInterface();

        /** @var Entity $attribute */
        foreach ($collection as $attribute) {
            $productInterface->addVariationAttribute($attribute->getCode());
        }

        return null;
    }
}
