<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Transformer\Api\Sales\Order;

use B2W\SkyHub\Model\Sales\Order\Address\Entity;
use B2W\SkyHub\Model\Transformer\Api\Sales\EntityAbstract;

/**
 * Class Address
 * @package B2W\SkyHub\Model\Transformer\Api\Sales\Order
 */
class Address extends EntityAbstract
{
    /**
     * @return Entity|mixed
     */
    protected function _getEntityInstance()
    {
        return new Entity();
    }
}
